import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/components/react_query_provider";
import "./globals.css";

const mainFont = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={mainFont.className}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
