import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/components/react_query_provider";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";

const mainFont = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={mainFont.className}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
